import { type ThemeConfig } from "antd";

export const lightMode: ThemeConfig = {
  token: {
    fontFamily: `
    'InterBlack', 
    'InterBold', 
    'InterExtraBold', 
    'InterExtraLight', 
    'InterLight', 
    'InterMedium', 
    'InterRegular', 
    'InterSemiBold', 
    'InterThin',
  `,
  },
  components: {
    Button: {
      defaultBg: "#5C61E6",
      colorText: "#fff",
      defaultBorderColor: "#5C61E6",
      colorPrimaryHover: "#464ce3",
      defaultHoverBg: "#464ce3",
      defaultHoverColor:"#fff",
      contentFontSize: 15,
      controlHeight:38
    },
    // Collapse: {
    //   fontSize: 17,
    //   headerPadding: "12px 16px",
    //   headerBg: "#F5F5F5",
    //   colorBgContainer: "#fff",
    // },
  },
};

// export const darkMode: ThemeConfig = {
//   token: {
//     cyan: "#EEF0F4",
//     green1: "#EDFCF5",
//     yellow1: "#FEFEE8",
//     red1: "#FDF4F3",
//     blue: "",
//     green2: "#ADEDCE",
//     yellow2: "#FBF98D",
//     red2: "#F9D2CF",
//     blue1: "",
//     green3: "#108B62",
//     yellow3: "#C69B08",
//     red3: "#CA4138",
//     blue2: "",
//     colorTextHeading: "#565B77",
//     colorText: "#1B1B1B",
//     colorBgBase: "#F8F8F8",
//     colorBorder: "#D7DDE6",
//     colorSuccess: "#D4F7E4",
//     colorError: "#FBE6E5",
//     colorInfoBg: "#ECF4FF",
//     colorInfoBorder: "#98BCFF",
//     colorFill: "#F5F7F9",
//     fontFamily: `
//     'FuturaRegular',
//     'FuturaMedium',
//     'FuturaBold',
//     'FuturaSemiBold',
//     sans-serif
//   `,
//   },
//   components: {
//     Collapse: {
//       fontSize: 17,
//       headerPadding: "24px 0px",
//       headerBg: "rgba(0,0,0,0.05)",
//     },
//     Progress: {
//       colorSuccess: "#19bc2f",
//       colorError: "rgb(231,202,15)",
//     },
//     Checkbox: {
//       colorPrimary: "#4062B5",
//       borderRadius: 0,
//       borderRadiusSM: 0,
//     },
//     Slider: {
//       handleColor: "#847379",
//       trackBg: "#847379",
//       trackHoverBg: "#847379",
//       handleActiveColor: "#847379",
//       colorPrimaryBorderHover: "#847379",
//       handleActiveOutlineColor: "rgb(132,115,121,0.2)",
//     },
//     Switch: {
//       colorPrimary: "rgb(170,122,36)",
//       colorPrimaryHover: "rgb(170,122,36)",
//     },
//     Card: {
//       headerBg: "rgb(255,255,255)",
//       colorText: "rgba(0,0,0,0.85)",
//       extraColor: "rgba(255,255,255,0.88)",
//       actionsBg: "rgb(255,255,255)",
//       colorBgContainer: "rgb(255,255,255)",
//       colorBorderSecondary: "rgba(215, 221, 230, 1)",
//       borderRadiusLG: 12,
//     },
//     Layout: {
//       headerBg: "white",
//       siderBg: "#141A52",
//       colorBorderBg: "red",
//     },
//     InputNumber: {
//       colorBgContainer: "rgb(255,255,255)",
//       controlHeight: 40,
//       borderRadius: 8,
//       colorBorder: "rgb(215,221,230)",
//       colorTextLabel: "#656C90",
//     },
//     Select: {
//       colorBgContainer: "rgb(255,255,255)",
//       controlHeight: 40,
//       borderRadius: 8,
//       colorBorder: "rgb(215,221,230)",
//       colorTextQuaternary: "rgb(47,49,60)",
//       colorTextPlaceholder: "#9CA8BE",
//       optionSelectedBg: "#9CA8BE",
//       colorTextLabel: "#656C90",
//     },
//     Input: {
//       colorBgContainer: "rgb(255,255,255)",
//       controlHeight: 40,
//       borderRadius: 8,
//       colorBorder: "rgb(203,203,203)",
//       colorTextPlaceholder: "#9CA8BE",
//       colorTextLabel: "#656C90",
//       colorPrimaryHover: "rgb(0,50,98)",
//       activeBorderColor: "rgb(0,50,98)",
//       colorBgContainerDisabled: "rgb(203,203,203)",
//       colorError: "rgb(233,67,53)",
//     },
//     DatePicker: {
//       colorBgContainer: "rgb(255,255,255)",
//       controlHeight: 40,
//       borderRadius: 8,
//       colorBorder: "rgb(215,221,230)",
//       colorTextDisabled: "rgb(47,49,60)",
//       colorTextPlaceholder: "#9CA8BE",
//       colorTextLabel: "#656C90",
//     },
//     Tabs: {
//       lineWidth: 1,
//       titleFontSize: 16,
//       itemColor: "#847379",
//       itemHoverColor: "#AA7A24",
//       itemSelectedColor: "#AA7A24",
//       itemActiveColor: "#AA7A24",
//       inkBarColor: "#AA7A24",
//       colorBorderSecondary: "#D7DDE6",
//       colorTextDescription: "black",
//     },
//     Table: {
//       headerBg: "white",
//       headerBorderRadius: 0,
//       fontSize: 13,
//       headerColor: "#656565",
//       borderColor: "rgb(215,221,230)",
//       colorText: "rgb(47,49,60)",
//       colorBgContainer: "rgb(255,255,255)",
//       footerBg: "#ffffff",
//     },
//     Button: {
//       controlHeight: 43,
//       colorPrimary: "#4062B5",
//       borderRadius: 0,
//       colorPrimaryHover: "#AA7A24",
//       colorLink: "#3D3D3D",
//       colorLinkHover: "#AA7A24",
//       colorIcon: "#2F313C",
//     },
//     Typography: {
//       fontSizeHeading2: 16,
//       fontSize: 14,
//     },
//     Menu: {
//       itemBg: "transparent",
//       colorText: "black",
//       itemColor: "black",
//       itemHoverBg: "transparent",
//       subMenuItemBg: "transparent",
//       itemHoverColor: "#aa7a24",
//       itemSelectedBg: "transparent",
//       itemSelectedColor: "black",
//       itemActiveBg: "transparent",
//       // iconMarginInlineEnd: 8,
//       popupBg: "transparent",
//     },
//     Statistic: {
//       contentFontSize: 18,
//       titleFontSize: 12,
//       colorTextHeading: "#565B77",
//       padding: 0,
//     },
//     Descriptions: {
//       colorTextSecondary: "rgb(0,0,0)",
//       // colorTextSecondary: "rgb(101,108,144)",
//       // colorTextTertiary: "#656C90",
//     },
//     Modal: {
//       headerBg: "transparent",
//       titleFontSize: 20,
//       fontWeightStrong: 1000,
//       titleLineHeight: 2.3,
//       borderRadiusLG: 16,
//       contentBg: "#FFFFFF",
//     },
//     Alert: {
//       borderRadiusLG: 12,
//       colorErrorBorder: "rgb(235,133,126)",
//       colorErrorBg: "rgb(251,230,229)",
//       colorError: "rgb(202,65,56)",
//       lineHeight: 1.1,
//     },
//     Form: {
//       labelColor: "#656565",
//       marginLG: 0,
//       labelColonMarginInlineEnd: 5,
//       verticalLabelPadding: "0 0 0px",
//       colorError: "rgb(255,0,4)",
//     },
//     Pagination: {
//       itemActiveBg: "#EEF0F4",
//     },
//     List: {
//       colorBorder: "#D7DDE6",
//       colorTextDescription: "#484C60",
//     },
//     Notification: {
//       colorError: "rgb(247,76,79)",
//       colorSuccess: "rgb(84,198,28)",
//       colorBgElevated: "#ffffff",
//       colorText: "#000000",
//       colorTextHeading: "#000000",
//     },
//     Breadcrumb: {
//       separatorColor: "#000000",
//       linkColor: "rgba(255,255,255,0.45)",
//       itemColor: "rgba(255,255,255,0.45)",
//       lastItemColor: "rgba(255,255,255,0.88)",
//       colorText: "rgba(255,255,255,0.88)",
//       linkHoverColor: "#AA7A24",
//       colorBgTextHover: "transparent",
//     },
//     Radio: {
//       buttonColor: "rgb(132,115,121)",
//       colorPrimaryActive: "rgb(250,243,230)",
//       colorPrimaryHover: "rgb(250,243,230)",
//       colorPrimaryBorder: "rgba(250,243,230,0)",
//       colorBorder: "rgba(255,255,255,0)",
//       buttonSolidCheckedActiveBg: "rgb(250,243,230)",
//       buttonSolidCheckedBg: "rgb(250,243,230)",
//       buttonCheckedBg: "rgb(255,255,255)",
//       buttonSolidCheckedHoverBg: "rgb(250,243,230)",
//       colorPrimary: "rgb(170,122,36)",
//       colorBgContainer: "rgba(255,255,255,0)",
//       buttonSolidCheckedColor: "rgb(222,217,218)",
//     },
//     Anchor: {
//       colorPrimary: "#AA7A24",
//       fontSize: 16,
//       lineHeight: 2.8,
//     },
//     Spin: {
//       colorPrimary: "#4062B5",
//     },
//   },
// };
